package com.ch.example;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BenefitMatch implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private String benefitCode;
	private String benefitType;
	private Boolean isPimary;
	private Boolean isuserAdded;
	private Integer weight;

	public BenefitMatch() {
	}

	public String getBenefitCode() {
		return this.benefitCode;
	}

	public void setBenefitCode(String benefitCode) {
		this.benefitCode = benefitCode;
	}

	public String getBenefitType() {
		return this.benefitType;
	}

	public void setBenefitType(String benefitType) {
		this.benefitType = benefitType;
	}

	public Boolean getIsPimary() {
		return this.isPimary;
	}

	public void setIsPimary(Boolean isPimary) {
		this.isPimary = isPimary;
	}

	public Boolean getIsuserAdded() {
		return this.isuserAdded;
	}

	public void setIsuserAdded(Boolean isuserAdded) {
		this.isuserAdded = isuserAdded;
	}

	public Integer getWeight() {
		return this.weight;
	}

	public void setWeight(Integer weight) {
		this.weight = weight;
	}

	public BenefitMatch(String benefitCode,
			String benefitType, Boolean isPimary,
			Boolean isuserAdded, Integer weight) {
		this.benefitCode = benefitCode;
		this.benefitType = benefitType;
		this.isPimary = isPimary;
		this.isuserAdded = isuserAdded;
		this.weight = weight;
	}

}