package com.ch.example;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ClaimLineAmountDetails implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private Integer copayAmount;
	private Integer notCoveredBilledAmount;
	private Integer allowedAmount;
	private Integer billedAmount;
	private Integer originalAllowedAmount;

	public ClaimLineAmountDetails() {
	}

	public Integer getCopayAmount() {
		return this.copayAmount;
	}

	public void setCopayAmount(Integer copayAmount) {
		this.copayAmount = copayAmount;
	}

	public Integer getNotCoveredBilledAmount() {
		return this.notCoveredBilledAmount;
	}

	public void setNotCoveredBilledAmount(
			Integer notCoveredBilledAmount) {
		this.notCoveredBilledAmount = notCoveredBilledAmount;
	}

	public Integer getAllowedAmount() {
		return this.allowedAmount;
	}

	public void setAllowedAmount(Integer allowedAmount) {
		this.allowedAmount = allowedAmount;
	}

	public Integer getBilledAmount() {
		return this.billedAmount;
	}

	public void setBilledAmount(Integer billedAmount) {
		this.billedAmount = billedAmount;
	}

	public Integer getOriginalAllowedAmount() {
		return this.originalAllowedAmount;
	}

	public void setOriginalAllowedAmount(Integer originalAllowedAmount) {
		this.originalAllowedAmount = originalAllowedAmount;
	}

	public ClaimLineAmountDetails(Integer copayAmount,
			Integer notCoveredBilledAmount,
			Integer allowedAmount, Integer billedAmount,
			Integer originalAllowedAmount) {
		this.copayAmount = copayAmount;
		this.notCoveredBilledAmount = notCoveredBilledAmount;
		this.allowedAmount = allowedAmount;
		this.billedAmount = billedAmount;
		this.originalAllowedAmount = originalAllowedAmount;
	}

}