package com.ch.example;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ClaimLine implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private String claimLineId;

	private java.util.List<BenefitMatch> benefitMatches;

	private ClaimLineAmountDetails claimLineAmountDetails;

	public ClaimLine() {
	}

	public String getClaimLineId() {
		return this.claimLineId;
	}

	public void setClaimLineId(String claimLineId) {
		this.claimLineId = claimLineId;
	}

	public java.util.List<BenefitMatch> getBenefitMatches() {
		return this.benefitMatches;
	}

	public void setBenefitMatches(
			java.util.List<BenefitMatch> benefitMatches) {
		this.benefitMatches = benefitMatches;
	}

	public ClaimLineAmountDetails getClaimLineAmountDetails() {
		return this.claimLineAmountDetails;
	}

	public void setClaimLineAmountDetails(
			ClaimLineAmountDetails claimLineAmountDetails) {
		this.claimLineAmountDetails = claimLineAmountDetails;
	}

	public ClaimLine(
			String claimLineId,
			java.util.List<BenefitMatch> benefitMatches,
			ClaimLineAmountDetails claimLineAmountDetails) {
		this.claimLineId = claimLineId;
		this.benefitMatches = benefitMatches;
		this.claimLineAmountDetails = claimLineAmountDetails;
	}

}