package com.ch.example;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Claim implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private String claimId;
	private String placeOfServiceCode;
	private String originalNetworkTier;
	private Boolean cob;
	private String partner;
	private String claimType;
	private Boolean memberSubmitted;
	private ProviderDetails providerDetails;
	private String billingTransparencyCategory;
	private Boolean adjustment;
	private AmountDetails amountDetails;
	private DateDetails dateDetails;

	public Claim() {
	}

	public String getClaimId() {
		return this.claimId;
	}

	public void setClaimId(String claimId) {
		this.claimId = claimId;
	}

	public String getPlaceOfServiceCode() {
		return this.placeOfServiceCode;
	}

	public void setPlaceOfServiceCode(String placeOfServiceCode) {
		this.placeOfServiceCode = placeOfServiceCode;
	}

	public String getOriginalNetworkTier() {
		return this.originalNetworkTier;
	}

	public void setOriginalNetworkTier(String originalNetworkTier) {
		this.originalNetworkTier = originalNetworkTier;
	}

	public Boolean getCob() {
		return this.cob;
	}

	public void setCob(Boolean cob) {
		this.cob = cob;
	}

	public String getPartner() {
		return this.partner;
	}

	public void setPartner(String partner) {
		this.partner = partner;
	}

	public String getClaimType() {
		return this.claimType;
	}

	public void setClaimType(String claimType) {
		this.claimType = claimType;
	}

	public Boolean getMemberSubmitted() {
		return this.memberSubmitted;
	}

	public void setMemberSubmitted(Boolean memberSubmitted) {
		this.memberSubmitted = memberSubmitted;
	}

	public ProviderDetails getProviderDetails() {
		return this.providerDetails;
	}

	public void setProviderDetails(
			ProviderDetails providerDetails) {
		this.providerDetails = providerDetails;
	}

	public String getBillingTransparencyCategory() {
		return this.billingTransparencyCategory;
	}

	public void setBillingTransparencyCategory(
			String billingTransparencyCategory) {
		this.billingTransparencyCategory = billingTransparencyCategory;
	}

	public Boolean getAdjustment() {
		return this.adjustment;
	}

	public void setAdjustment(Boolean adjustment) {
		this.adjustment = adjustment;
	}

	public AmountDetails getAmountDetails() {
		return this.amountDetails;
	}

	public void setAmountDetails(
			AmountDetails amountDetails) {
		this.amountDetails = amountDetails;
	}

	public DateDetails getDateDetails() {
		return this.dateDetails;
	}

	public void setDateDetails(DateDetails dateDetails) {
		this.dateDetails = dateDetails;
	}

	public Claim(String claimId, String placeOfServiceCode,
			String originalNetworkTier, Boolean cob,
			String partner, String claimType,
			Boolean memberSubmitted,
			ProviderDetails providerDetails,
			String billingTransparencyCategory,
			Boolean adjustment,
			AmountDetails amountDetails,
			DateDetails dateDetails) {
		this.claimId = claimId;
		this.placeOfServiceCode = placeOfServiceCode;
		this.originalNetworkTier = originalNetworkTier;
		this.cob = cob;
		this.partner = partner;
		this.claimType = claimType;
		this.memberSubmitted = memberSubmitted;
		this.providerDetails = providerDetails;
		this.billingTransparencyCategory = billingTransparencyCategory;
		this.adjustment = adjustment;
		this.amountDetails = amountDetails;
		this.dateDetails = dateDetails;
	}

}