package com.ch.example;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ProviderDetails implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private ServiceProvider serviceProvider;

	public ProviderDetails() {
	}

	public ServiceProvider getServiceProvider() {
		return this.serviceProvider;
	}

	public void setServiceProvider(
			ServiceProvider serviceProvider) {
		this.serviceProvider = serviceProvider;
	}

	public ProviderDetails(
			ServiceProvider serviceProvider) {
		this.serviceProvider = serviceProvider;
	}

}