package com.ch.example;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RulesOutPut implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private String link;
	private String ruleSet;
	private String description;
	private String type;
	private String action;
	private String start;
	private String end;

	public RulesOutPut() {
	}

	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	public String getRuleSet() {
		return this.ruleSet;
	}

	public void setRuleSet(String ruleSet) {
		this.ruleSet = ruleSet;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	public String getStart() {
		return this.start;
	}

	public void setStart(String start) {
		this.start = start;
	}

	public String getEnd() {
		return this.end;
	}

	public void setEnd(String end) {
		this.end = end;
	}

	public RulesOutPut(String link, String ruleSet,
			String description, String type,
			String action, String start,
			String end) {
		this.link = link;
		this.ruleSet = ruleSet;
		this.description = description;
		this.type = type;
		this.action = action;
		this.start = start;
		this.end = end;
	}

}