package com.ch.example;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ServiceProvider implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private String addressLine1;
	private String addressLine2;
	private String stateCode;

	public ServiceProvider() {
	}

	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	public String getStateCode() {
		return this.stateCode;
	}

	public void setStateCode(String stateCode) {
		this.stateCode = stateCode;
	}

	public ServiceProvider(String addressLine1,
			String addressLine2, String stateCode) {
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.stateCode = stateCode;
	}

}